services:
  #================================================================================================
  # MARIADB
  #================================================================================================
  db_mariadb:
    image: mariadb:10.11.7-jammy
    container_name: mariadb_cdk
    ports:
      - "7654:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb_cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./mariadb_log/logs:/var/lib/mysql/logs/
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_mariadb
      MYSQL_PASSWORD: user_Password123
     # MYSQL_TCP_PORT: 3307  
    networks:
      - monalisa
  #================================================================================================
  # PHPMYADMIN
  #================================================================================================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cdk
    depends_on:
      - db_mariadb    
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/config:/config  
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123
      PMA_HOST: db_mariadb
      UPLOAD_LIMIT: 300M
    networks:
      - monalisa

   #================================================================================================
  # APPLICATION
  #================================================================================================     
  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: nest-docker-mariadb
      environment:
        - PORT=${PORT}
      ports:
        - '3000:3000'
      depends_on:
        - db_mariadb
      volumes:
        - ./src:/app/src
networks:
  monalisa: